# # Resolve react_native_pods.rb with node to allow for hoisting
# require Pod::Executable.execute_command('node', ['-p',
#   'require.resolve(
#     "react-native/scripts/react_native_pods.rb",
#     {paths: [process.argv[1]]},
#   )', __dir__]).strip

# platform :ios, min_ios_version_supported
# prepare_react_native_project!

# linkage = ENV['USE_FRAMEWORKS']
# if linkage != nil
#   Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
#   use_frameworks! :linkage => linkage.to_sym
# end

# target 'mobile' do
#   config = use_native_modules!

#   # use_react_native!(
#   #   :path => config[:reactNativePath],
#   #   # An absolute path to your application root.
#   #   :app_path => "#{Pod::Config.instance.installation_root}/.."
#   # )

#   use_react_native!(
#   :path => config[:reactNativePath],
#   :app_path => "#{Pod::Config.instance.installation_root}/..",

#   # Required for monorepos using react-native-config
#   :fabric_enabled => false,     # 👈 turn off Fabric for now
#   :hermes_enabled => true
# )

#   post_install do |installer|
#     react_native_post_install(
#       installer,
#       config[:reactNativePath],
#       :mac_catalyst_enabled => false,
#       # :ccache_enabled => true
#     )
#   end
# end

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native/scripts/react_native_pods.rb'

platform :ios, '13.0'

target 'mobile' do
  config = use_native_modules!

  use_react_native!(
    :path => config["reactNativePath"],
    :hermes_enabled => true, # Hermes ON
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Firebase (autolinking supported, but declaring them is safe)
  pod 'FirebaseCore'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseMessaging'
  pod 'FirebaseAnalytics'
  pod 'FirebaseCrashlytics'
  pod 'FirebaseRemoteConfig'

  target 'mobileTests' do
    inherit! :search_paths
  end

  post_install do |installer|
    react_native_post_install(installer)

    # Ensures RN 0.80+ + Xcode 16+ don’t break
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["ENABLE_USER_SCRIPT_SANDBOXING"] = "NO"
        config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "13.0"
      end
    end
  end
end
