import type { FunctionCopyFilesProps, FunctionProps } from "sst/constructs";

/**
 * Paths are relative to `services/backend` (where sst.config.ts lives).
 * Prisma is hoisted to the monorepo root by yarn workspaces.
 */
const ROOT_NODE_MODULES = "../../node_modules";

/** Generated by `yarn prisma:generate` at the monorepo root. */
export const PRISMA_COPY_FILES: FunctionCopyFilesProps[] = [
  {
    from: `${ROOT_NODE_MODULES}/.prisma/client`,
    to: "node_modules/.prisma/client",
  },
  {
    from: `${ROOT_NODE_MODULES}/@prisma/client`,
    to: "node_modules/@prisma/client",
  },
  {
    from: `${ROOT_NODE_MODULES}/@prisma/client-runtime-utils`,
    to: "node_modules/@prisma/client-runtime-utils",
  },
];

export const PRISMA_FUNCTION_DEFAULTS: Pick<
  FunctionProps,
  "copyFiles" | "nodejs"
> = {
  copyFiles: PRISMA_COPY_FILES,
  nodejs: {
    // Install adapter + pg for Lambda (linux). Do NOT install @prisma/client —
    // npm ships a generic client without our generated schema/wasm.
    install: ["pg", "@prisma/adapter-pg"],
    esbuild: {
      external: [
        "@prisma/client",
        ".prisma/client",
        "@prisma/adapter-pg",
        "@prisma/client-runtime-utils",
        "@prisma/driver-adapter-utils",
        "pg",
      ],
    },
  },
};
